<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSyKjiOx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSyKjiOx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSyKjiOx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSyKjiOx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSyKjiOx\App_KernelDevDebugContainer([
    'container.build_hash' => 'SyKjiOx',
    'container.build_id' => '9d0f6c98',
    'container.build_time' => 1699817971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSyKjiOx');
