<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG6XNxV1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG6XNxV1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG6XNxV1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG6XNxV1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG6XNxV1\App_KernelDevDebugContainer([
    'container.build_hash' => 'G6XNxV1',
    'container.build_id' => '0eb44581',
    'container.build_time' => 1697974052,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG6XNxV1');
